"""Pre-build: embed the web UI into the firmware as PROGMEM byte arrays.

Percorso A (WLED / LuxDMX style): instead of serving the UI from a separate
LittleFS partition, compile it into the app image. The OTA and the installer
then need only a single .bin — there is no filesystem image to ship or flash
alongside the firmware.

What gets embedded:
  - shared shell: index.html, app.js, output-card.js, style.css, dmxmonitor.html
  - the fixture.js of the ACTIVE fixture only (from the RAVLIGHT_FIXTURE_* flag)
  - images: Background.jpg, RavLightLogo.png, favicon.png, Iicon.png

Text assets (html/js/css) are gzipped; images are embedded as-is (already
compressed). The generated header exposes a WEB_ASSETS[] lookup table the
web server walks in sendAsset(). Written to $BUILD_DIR so it is per-env and
never committed; $BUILD_DIR is added to the include path.

LittleFS is NOT removed — it still holds runtime data (recorder scenes,
default_config.json) — it just no longer carries the UI.
"""
import gzip
import os
from pathlib import Path

Import("env")  # noqa: F821 — PlatformIO injects this

ROOT      = Path(env["PROJECT_DIR"])       # noqa: F821
DATA      = ROOT / "data"
BUILD_DIR = Path(env.subst("$BUILD_DIR"))  # noqa: F821
OUT       = BUILD_DIR / "web_assets.h"

# Shared shell assets: (source path relative to data/, served path, content-type, gzip?)
SHARED = [
    ("index.html",       "/index.html",       "text/html",              True),
    ("app.js",           "/app.js",           "application/javascript", True),
    ("output-card.js",   "/output-card.js",   "application/javascript", True),
    ("style.css",        "/style.css",        "text/css",               True),
    ("dmxmonitor.html",  "/dmxmonitor.html",  "text/html",              True),
    ("Background.jpg",   "/Background.jpg",    "image/jpeg",             False),
    ("RavLightLogo.png", "/RavLightLogo.png", "image/png",              False),
    ("favicon.png",      "/favicon.png",      "image/png",              False),
    ("Iicon.png",        "/Iicon.png",        "image/png",              False),
]

# Which fixture is this build? — pick its fixture.js.
FIXTURES = {
    "RAVLIGHT_FIXTURE_ELYON":  "elyon",
    "RAVLIGHT_FIXTURE_VEYRON": "veyron",
    "RAVLIGHT_FIXTURE_ORION":  "orion",
    "RAVLIGHT_FIXTURE_AXON":   "axon",
}


def active_fixture():
    # The RAVLIGHT_FIXTURE_* flags come from the env's build_flags. At pre-
    # script time they're most reliably read from the expanded BUILD_FLAGS
    # string; fall back to CPPDEFINES too.
    hay = env.subst("$BUILD_FLAGS")            # noqa: F821
    for d in env.get("CPPDEFINES", []):        # noqa: F821
        hay += " " + (d[0] if isinstance(d, (list, tuple)) else str(d))
    for flag, name in FIXTURES.items():
        if flag in hay:
            return name
    return None


def c_ident(served_path):
    return "asset_" + "".join(ch if ch.isalnum() else "_" for ch in served_path.strip("/"))


def emit_array(fh, ident, data):
    fh.write(f"static const uint8_t {ident}[] PROGMEM = {{\n")
    for i in range(0, len(data), 20):
        fh.write("  " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    fh.write("};\n")


def build_list():
    items = list(SHARED)
    fx = active_fixture()
    if fx:
        src = f"{fx}/fixture.js"
        if (DATA / src).is_file():
            items.append((src, "/fixture.js", "application/javascript", True))
    return items


def main():
    items = build_list()
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    raw_total = emb_total = 0

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by scripts/embed_assets.py — do not edit.\n")
        fh.write("#pragma once\n#include <stdint.h>\n#include <pgmspace.h>\n\n")
        fh.write("struct WebAsset { const char* path; const uint8_t* data; "
                 "unsigned len; bool gzip; const char* ctype; };\n\n")

        for src, served, ctype, do_gz in items:
            p = DATA / src
            if not p.is_file():
                continue
            raw = p.read_bytes()
            data = gzip.compress(raw, 9) if do_gz else raw
            ident = c_ident(served)
            emit_array(fh, ident, data)
            entries.append((served, ident, len(data), "true" if do_gz else "false", ctype))
            raw_total += len(raw)
            emb_total += len(data)

        fh.write("\nstatic const WebAsset WEB_ASSETS[] = {\n")
        for served, ident, ln, gz, ctype in entries:
            fh.write(f'  {{ "{served}", {ident}, {ln}, {gz}, "{ctype}" }},\n')
        fh.write("};\n")
        fh.write(f"static const int WEB_ASSETS_N = {len(entries)};\n")

    # Make the generated header findable by #include "web_assets.h"
    env.Append(CPPPATH=[str(BUILD_DIR)])  # noqa: F821

    # Expose custom_fw_name to the firmware as RAVLIGHT_FW_BASE — the OTA
    # module uses it to build the per-board manifest/binary URL on the feed.
    base = env.GetProjectOption("custom_fw_name") or "unknown"  # noqa: F821
    env.Append(CPPDEFINES=[("RAVLIGHT_FW_BASE", env.StringifyMacro(base))])  # noqa: F821

    print(f"[embed_assets] {len(entries)} assets -> web_assets.h "
          f"({raw_total} B raw -> {emb_total} B embedded, fixture={active_fixture()}, base={base})")


main()
