#include "webserver_manager.h"
#include "config.h"
#include "fixture_config.h"
#include <LittleFS.h>
#include "network_manager.h"
#include <Update.h>
#include "runtime.h"
#include <ArduinoJson.h>
#include <AsyncJson.h>
#include <Ticker.h>
#include "dmx_manager.h"
#include "core/stats.h"
#include "core/ota_update.h"
#include "web_assets.h"   // generated by scripts/embed_assets.py ($BUILD_DIR)
#include "core/oled.h"
#include <memory>
#include <WiFi.h>
#include <esp_timer.h>

#ifdef RAVLIGHT_MODULE_EFFECTS
#include "effects.h"
#endif

#ifdef RAVLIGHT_MODULE_ETHERNET
#include <ETH.h>
#endif

#ifdef RAVLIGHT_MODULE_TEMP
#include "temp_sensor.h"
#endif

#include "fixture_webserver.h"

#ifdef RAVLIGHT_MODULE_RECORDER
#include "dmx_recorder.h"
#endif
#ifdef RAVLIGHT_MODULE_DISCOVERY
#include "discovery_shared.h"
#include "discovery_udp.h"
#include "discovery_espnow.h"
static Ticker espnowScanTicker;
static Ticker espnowCmdTicker;
static Ticker espnowCmdRestoreTicker;
static struct {
    char hwMac[18];
    char cmd[12];
    char ssid[64];
    char pwd[64];
} s_pendingCmd;
#endif

extern uint32_t totalRuntime;
extern uint32_t currentRuntime;
extern int16_t WiFiScanStatus;

#ifdef RAVLIGHT_MODULE_TEMP
extern float SensTemp;
#endif

static AsyncWebServer server(80);
extern String ScannedSSID;
Ticker restartTimer;

AsyncWebServer& getInstance() {
    return server;
}


// Serve a text asset preferring its pre-gzipped sibling when present. The
// scripts/gzip_assets.py pre-build hook produces <path>.gz next to each
// .html/.css/.js asset; here we transparently pick the smaller copy and
// advertise Content-Encoding: gzip so the browser inflates on the fly.
//
// Cache-Control: when the browser fires the 4-5 script requests in parallel
// after first paint, ESPAsyncWebServer + LittleFS can drop one of them mid-
// stream (EMPTY_RESPONSE on the smaller files, CONTENT_LENGTH_MISMATCH on
// the bigger ones — a TCP TX buffer / file-handle pressure issue). With
// max-age=86400 + immutable the browser keeps the result and never refetches
// while the gzip filename stays stable, so the parallel-request pile-up only
// happens once per cold visit. Tagged assets ship a new gzip on each rebuild,
// and the asset paths themselves are byte-stable, so a stale cache mostly
// just means "looks like the last RavLight" — a hard reload pulls the
// latest. Reduces visible "Loading…" hangs to first connect only.
static void sendAsset(AsyncWebServerRequest *request,
                      const char *path, const char *contentType) {
    // ETag validator tied to the firmware version. Assets are byte-stable
    // within a build and only change on a firmware bump, so FW_VERSION is a
    // perfect validator: a matching If-None-Match lets us answer 304 (no body)
    // instead of re-streaming app.js / fixture.js / style.css on every reload.
    // The browser keeps its cached copy but still picks up a fresh UI after an
    // OTA, because the version — and thus the ETag — changes. This is what
    // turns the "no-cache, must-revalidate" policy below from a full re-download
    // every load into a cheap conditional GET.
    static const char* kETag = "\"" FW_VERSION "\"";
    if (request->hasHeader("If-None-Match")) {
        const AsyncWebHeader* h = request->getHeader("If-None-Match");
        if (h && h->value() == kETag) {
            AsyncWebServerResponse *nm = request->beginResponse(304);
            nm->addHeader("ETag", kETag);
            request->send(nm);
            return;
        }
    }

    AsyncWebServerResponse *r = nullptr;

    // Percorso A: the UI is embedded in the firmware (see embed_assets.py).
    // Serve straight from PROGMEM — no LittleFS image needed for the UI, so
    // the OTA and installer ship a single .bin. LittleFS is only touched as
    // a fallback (e.g. a dev board that still has an old filesystem uploaded).
    for (int i = 0; i < WEB_ASSETS_N; i++) {
        if (strcmp(WEB_ASSETS[i].path, path) != 0) continue;
        // NB: beginResponse (with explicit len), NOT beginResponse_P — in this
        // fork beginResponse_P takes no length arg, so a length passed there is
        // read as the template callback and the response breaks (HTTP 500).
        // ESP32 flash is memory-mapped, so PROGMEM data is read directly.
        r = request->beginResponse(200, WEB_ASSETS[i].ctype,
                                   WEB_ASSETS[i].data, WEB_ASSETS[i].len);
        if (WEB_ASSETS[i].gzip) r->addHeader("Content-Encoding", "gzip");
        break;
    }
    if (!r) {
        // Fallback: LittleFS (gzip sibling first, then raw).
        String gz = String(path) + ".gz";
        if (LittleFS.exists(gz)) {
            r = request->beginResponse(LittleFS, gz, contentType);
            r->addHeader("Content-Encoding", "gzip");
        } else {
            r = request->beginResponse(LittleFS, path, contentType);
        }
    }
    // Cache policy is per-asset-type:
    //   .js / .html / .css → must-revalidate every reload. These get fixed
    //       across firmware bumps, and stale copies cause functional bugs
    //       (typical symptom: UI not picking up server-side changes because
    //       applyConfig in cached app.js doesn't have the new fields).
    //   everything else (images, fonts) → 1-hour cache. Background.jpg is
    //       25 KB and changes rarely; serving it from cache absorbs the
    //       parallel-request burst on subsequent reloads.
    const char* p = path;
    bool textAsset = false;
    while (*p) p++;
    if (p - path >= 3) {
        const char* ext = p - 3;
        if (!strcmp(ext, ".js") || !strcmp(p - 4, "html") || !strcmp(p - 4, ".css"))
            textAsset = true;
    }
    if (textAsset) {
        r->addHeader("Cache-Control", "no-cache, must-revalidate");
    } else {
        r->addHeader("Cache-Control", "public, max-age=3600");
    }
    // Version-keyed validator so reloads revalidate cheaply (304) yet a new
    // firmware always invalidates the cache. See the note at the top of the fn.
    r->addHeader("ETag", kETag);
    request->send(r);
}

void initWebServer() {
    if (!LittleFS.begin(false)) {
        // Do not auto-format: a SPIFFS partition from older firmware must be re-flashed
        // via uploadfs, not silently wiped. Server still starts to allow OTA recovery.
        Serial.println("[WS] LittleFS mount failed — recorder/config storage unavailable (UI is embedded, still served)");
    }

    // --- Static assets (shared) — served from embedded PROGMEM via sendAsset ---
    server.on("/Background.jpg", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/Background.jpg", "image/jpeg");
    });
    server.on("/RavLightLogo.png", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/RavLightLogo.png", "image/png");
    });
    server.on("/favicon.png", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/favicon.png", "image/png");
    });
    server.on("/Iicon.png", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/Iicon.png", "image/png");
    });
    server.on("/style.css", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/style.css", "text/css");
    });
    server.on("/dmxmonitor", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/dmxmonitor.html", "text/html");
    });

    // --- Root page (SPA shell — static) ---
    // index.html is now a small (~6 KB) SPA shell that loads app.js + fixture.js
    // and fetches /api/{features,status,config} for state. No server-side template
    // engine — page rendering is the client's job, the firmware just streams the
    // file. Old chunked handler (writeHTMLFromFile state machine) is retained
    // below for reference but unused; will be removed in the cleanup commit.
    server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
        // index.html is always embedded in the firmware (see embed_assets.py),
        // so sendAsset serves it from PROGMEM regardless of the LittleFS state.
        sendAsset(request, "/index.html", "text/html");
    });
    server.on("/app.js", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/app.js", "application/javascript");
    });
    server.on("/output-card.js", HTTP_GET, [](AsyncWebServerRequest *request) {
        sendAsset(request, "/output-card.js", "application/javascript");
    });
    server.on("/fixture.js", HTTP_GET, [](AsyncWebServerRequest *request) {
        // embed_assets.py embeds the active fixture's fixture.js as "/fixture.js".
        sendAsset(request, "/fixture.js", "application/javascript");
    });


    // --- WiFi scan (shared) ---
    server.on("/scanWiFi", HTTP_GET, [](AsyncWebServerRequest *request) {
        scanWiFiNetworks();
        request->send(200, "text/plain", "Scanning");
    });
    server.on("/getWiFiList", HTTP_GET, [](AsyncWebServerRequest *request) {
        request->send(200, "application/json", requestWiFiNetworks());
    });

    // --- Unified smart save ---
    // Applies live params immediately; restarts only if network/ID params changed.
    // Response: JSON {"restart": bool, "newIp": "x.x.x.x"}
    server.on("/save", HTTP_POST, [](AsyncWebServerRequest *request) {
        bool needsRestart = false;
        String newIp = netConfig.currentip;

        // --- Live params: apply immediately, no restart ---
        if (request->hasParam("autoSceneSlot", true)) {
            uint8_t v = (uint8_t)request->getParam("autoSceneSlot", true)->value().toInt();
            if (v != dmxConfig.autoSceneSlot) {
                dmxConfig.autoSceneSlot = v;
#ifdef RAVLIGHT_MODULE_RECORDER
                if (dmxConfig.dmxInput == AUTO_SCENE) {
                    stopAutoScene();
                    startAutoScene(dmxConfig.autoSceneSlot);
                }
#endif
            }
        }
        if (request->hasParam("dmxInput", true)) {
            uint16_t v = request->getParam("dmxInput", true)->value().toInt();
            if (v != dmxConfig.dmxInput) {
                dmxConfig.dmxInput = v;
                reinitDMXInput();
            }
        }
        if (request->hasParam("startUniverse", true)) {
            uint16_t v = request->getParam("startUniverse", true)->value().toInt();
            if (v != dmxConfig.startUniverse) {
                dmxConfig.startUniverse = v;
                reinitUniverse(v);
            }
        }
        if (request->hasParam("dmxOutput", true) != dmxConfig.dmxOutputEnabled) {
            bool v = request->hasParam("dmxOutput", true);
            dmxConfig.dmxOutputEnabled = v;
            reinitDMXOutput(v);
        }
        handleFixtureSaveParams(request, needsRestart);

        // --- Restart-required params (restart only when value actually changed) ---
        if (request->hasParam("ID_fixture", true)) {
            String v = request->getParam("ID_fixture", true)->value();
            if (v != setConfig.ID_fixture) { setConfig.ID_fixture = v; needsRestart = true; }
        }
        if (request->hasParam("ssid", true)) {
            String v = request->getParam("ssid", true)->value();
            if (v != netConfig.wifiSSID) { netConfig.wifiSSID = v; needsRestart = true; }
        }
        if (request->hasParam("password", true)) {
            String v = request->getParam("password", true)->value();
            if (v != netConfig.wifiPassword) { netConfig.wifiPassword = v; needsRestart = true; }
        }
        bool newDhcp = request->hasParam("dhcp", true);
        if (newDhcp != netConfig.dhcp) {
            netConfig.dhcp = newDhcp;
            needsRestart = true;
        }
        if (request->hasParam("ip", true)) {
            String v = request->getParam("ip", true)->value();
            if (v != netConfig.ip) {
                netConfig.ip = v;
                if (!netConfig.dhcp) newIp = v;
                needsRestart = true;
            }
        }
        if (request->hasParam("subnet", true)) {
            String v = request->getParam("subnet", true)->value();
            if (v != netConfig.subnet) { netConfig.subnet = v; needsRestart = true; }
        }
        if (request->hasParam("gateway", true)) {
            String v = request->getParam("gateway", true)->value();
            if (v != netConfig.gateway) { netConfig.gateway = v; needsRestart = true; }
        }

        saveConfig();

        DynamicJsonDocument resp(192);
        resp["restart"]  = needsRestart;
        resp["newIp"]    = newIp;
        resp["mdnsHost"] = "rav" + setConfig.ID_fixture + ".local";
        resp["connType"] = getConnectionMode();
        String respStr;
        serializeJson(resp, respStr);
        request->send(200, "application/json", respStr);

        if (needsRestart)
            scheduleRestart();
    });

    // --- Reset to defaults ---
    server.on("/reset", HTTP_POST, [](AsyncWebServerRequest *request) {
        resetConfig();
        request->send(200, "text/plain", "Configuration reset to defaults.");
        scheduleRestart();
    });
    // --- Reset to defaults ---
    server.on("/restart", HTTP_POST, [](AsyncWebServerRequest *request) {
        request->send(200, "text/plain", "Restarting...");
        scheduleRestart();
    });
    // --- Runtime (shared) ---
    server.on("/runtime", HTTP_GET, [](AsyncWebServerRequest *request) {
        request->send(200, "text/plain", String(currentRuntime));
    });
    server.on("/truntime", HTTP_GET, [](AsyncWebServerRequest *request) {
        request->send(200, "text/plain", String(totalRuntime));
    });

    // --- Temperature sensor module ---
#ifdef RAVLIGHT_MODULE_TEMP
    server.on("/temperature", HTTP_GET, [](AsyncWebServerRequest *request) {
        request->send(200, "text/plain", String(SensTemp));
    });
#endif

    // --- DMX activity status (shared by all fixtures + UI header chip) ---
    server.on("/dmxstatus", HTTP_GET, [](AsyncWebServerRequest *request) {
        String json = String("{\"active\":") + (dmxIsActive() ? "true" : "false") + "}";
        request->send(200, "application/json", json);
    });

    // --- DMX Recorder module routes ---
#ifdef RAVLIGHT_MODULE_RECORDER
    server.on("/startRecording", HTTP_GET, [](AsyncWebServerRequest *request) {
        if (request->hasParam("scene")) {
            int scene = request->getParam("scene")->value().toInt();
            startSceneRecording(scene);
            request->send(200, "text/plain", "Recording scene " + String(scene + 1));
        } else {
            request->send(400, "text/plain", "Missing scene parameter");
        }
    });

    server.on("/recordingStatus", HTTP_GET, [](AsyncWebServerRequest *request) {
        String json = isRecording ? "{\"recording\":true}" : "{\"recording\":false}";
        request->send(200, "application/json", json);
    });

    server.on("/listScenes", HTTP_GET, [](AsyncWebServerRequest *request) {
        String response = "Scenes:\n";
        for (int i = 0; i < 4; i++) {
            String fileName = "/scene_" + String(i) + ".bin";
            response += "Scene " + String(i) + (LittleFS.exists(fileName) ? " available" : " empty") + "\n";
        }
        request->send(200, "text/plain", response);
    });
#endif // RAVLIGHT_MODULE_RECORDER

    // --- Config upload/download (shared) ---
    // Upload: parse JSON directly into in-memory structs → save to NVS → restart
    server.on("/upload_config", HTTP_POST,
        [](AsyncWebServerRequest *request) {},
        NULL,
        [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total) {
            DynamicJsonDocument doc(4096);
            if (deserializeJson(doc, (char*)data, len)) {
                request->send(400, "text/plain", "JSON parse error");
                return;
            }
            applyConfigJson(doc);
            saveConfig();
            request->send(200, "text/plain", "OK");
            scheduleRestart();
        }
    );

    // Download: serialize from in-memory structs (always up-to-date with NVS)
    server.on("/download_config", HTTP_GET, [](AsyncWebServerRequest *request) {
        DynamicJsonDocument doc(4096);
        doc["version"] = 2;
        doc["board"]   = BOARD_NAME;
        doc["project"] = PROJECT_NAME;
        doc["ID_fixture"] = setConfig.ID_fixture;

        JsonObject net = doc.createNestedObject("network");
        net["id"]       = setConfig.ID_fixture;
        net["ssid"]     = netConfig.wifiSSID;
        net["password"] = netConfig.wifiPassword;
        net["dhcp"]     = netConfig.dhcp;
        net["ip"]       = netConfig.ip;
        net["subnet"]   = netConfig.subnet;
        net["gateway"]  = netConfig.gateway;
        net["espnow"]   = netConfig.espnowEnabled;

        JsonObject dmx = doc.createNestedObject("dmx");
        dmx["input"]    = dmxConfig.dmxInput;
        dmx["universe"] = dmxConfig.startUniverse;
#ifdef RAVLIGHT_MODULE_DMX_PHYSICAL
        dmx["output"]   = dmxConfig.dmxOutputEnabled;
#endif

        JsonObject fix = doc.createNestedObject("fixture");
        fixtureConfigSerialize(fix);

        String output;
        serializeJsonPretty(doc, output);
        request->send(200, "application/json", output);
    });

    // ─── JSON API for the SPA frontend ──────────────────────────────────────
    // Same shape as /download_config but smaller (compact, not pretty) and
    // intended for client-side rendering.
    server.on("/api/config", HTTP_GET, [](AsyncWebServerRequest *request) {
        DynamicJsonDocument doc(4096);
        doc["version"]    = 2;
        doc["board"]      = BOARD_NAME;
        doc["project"]    = PROJECT_NAME;
        doc["ID_fixture"] = setConfig.ID_fixture;

        JsonObject net = doc.createNestedObject("network");
        net["id"]       = setConfig.ID_fixture;
        net["ssid"]     = netConfig.wifiSSID;
        net["password"] = netConfig.wifiPassword;
        net["dhcp"]     = netConfig.dhcp;
        net["ip"]       = netConfig.ip;
        net["subnet"]   = netConfig.subnet;
        net["gateway"]  = netConfig.gateway;
        net["espnow"]   = netConfig.espnowEnabled;

        JsonObject dmx = doc.createNestedObject("dmx");
        dmx["input"]    = dmxConfig.dmxInput;
        dmx["universe"] = dmxConfig.startUniverse;
#ifdef RAVLIGHT_MODULE_DMX_PHYSICAL
        dmx["output"]   = dmxConfig.dmxOutputEnabled;
#endif
#ifdef RAVLIGHT_MODULE_RECORDER
        dmx["autoSceneSlot"] = dmxConfig.autoSceneSlot;
#endif
#ifdef RAVLIGHT_MODULE_EFFECTS
        // Mirror serializeDmx() in config.cpp so the UI's loadConfig sees
        // the current effects state. Without this the panel always resets
        // to the JS defaults (Solid red, full intensity, mid speed) on
        // page reload — losing the user's last picks.
        {
            JsonObject fx = dmx.createNestedObject("effects");
            fx["effect"]       = effectsConfig.effect;
            fx["speed"]        = effectsConfig.speed;
            fx["r"]            = effectsConfig.r;
            fx["g"]            = effectsConfig.g;
            fx["b"]            = effectsConfig.b;
            fx["intensity"]    = effectsConfig.intensity;
            fx["rgbw"]         = effectsConfig.rgbw_mode;
            fx["white"]        = effectsConfig.white;
            fx["strobe_rgb"]   = effectsConfig.strobeRgb;
            fx["strobe_white"] = effectsConfig.strobeWhite;
        }
#endif

        JsonObject fix = doc.createNestedObject("fixture");
        fixtureConfigSerialize(fix);

        String out;
        serializeJson(doc, out);
        request->send(200, "application/json", out);
    });

    // Per-universe timing diagnostic. Samples last_seen_ms for every
    // registered universe over a 500 ms window (server-side sleep-free
    // — we snapshot twice with time in between via successive requests
    // isn't ideal, so we just report "millis since last packet" for each
    // universe right now). Lets us tell whether a subset of universes
    // (typically the high-numbered burst-tail) has systematically bigger
    // last-packet gaps than the low-numbered ones.
    server.on("/api/universe-timing", HTTP_GET, [](AsyncWebServerRequest *request) {
        DynamicJsonDocument doc(1024);
        JsonArray arr = doc.createNestedArray("universes");
        uint32_t now = millis();
        for (uint8_t i = 0; i < dmxUniverseCount(); i++) {
            uint16_t u    = dmxUniverseAt(i);
            uint32_t last = getUniverseLastSeen(u);
            JsonObject o = arr.createNestedObject();
            o["u"]        = u;
            o["last_ms"]  = last;
            o["age_ms"]   = last ? (now - last) : 0;
        }
        String out;
        serializeJson(doc, out);
        request->send(200, "application/json", out);
    });

    // Runtime info — what the SPA shows in the header / status panel.
    server.on("/api/i2c", HTTP_GET, [](AsyncWebServerRequest *request) {
        // Returns the OLED module's init diagnostic — the I²C scan result
        // and whether u8g2 actually came up. Plain text for easy curl.
        request->send(200, "text/plain", oledDiag());
    });
    server.on("/api/status", HTTP_GET, [](AsyncWebServerRequest *request) {
        DynamicJsonDocument doc(640);
        doc["fw"]            = FW_VERSION;
        doc["board"]         = BOARD_NAME;
        doc["project"]       = PROJECT_NAME;
        doc["id"]            = setConfig.ID_fixture;
        doc["mode"]          = getConnectionMode();
        doc["ip"]            = netConfig.currentip;
        doc["mac"]           = WiFi.macAddress();
        doc["mdns"]          = "rav" + setConfig.ID_fixture + ".local";
        // RSSI only meaningful on WiFi STA — ETH and SoftAP just emit 0.
        if (WiFi.status() == WL_CONNECTED) doc["rssi"] = (int)WiFi.RSSI();
        else                               doc["rssi"] = 0;
        // Real elapsed seconds since boot (esp_timer is microseconds since
        // boot — divide by 1e6) — independent of the per-minute counter
        // that runtime.cpp persists to NVS.
        doc["uptime_sec"]    = (uint32_t)(esp_timer_get_time() / 1000000ULL);
        // Total operating hours across all boots. currentRuntime/
        // totalRuntime in runtime.cpp are incremented once per minute
        // (despite the legacy "total_hours" NVS key name), so divide by
        // 60 to surface integer hours to consumers — no more confusing
        // "Total: 00:14" headers that actually meant 14 minutes.
        doc["total_hours"]   = totalRuntime / 60;
        doc["heap_free"]     = ESP.getFreeHeap();
        doc["heap_min"]      = ESP.getMinFreeHeap();
#ifdef RAVLIGHT_MODULE_TEMP
        doc["temp"] = SensTemp;
#endif
        doc["dmx_active"]    = dmxIsActive();
        doc["fps"]           = dmxSourceFps();
        // Legacy field names kept transiently so old UIs / scripts don't
        // 500 on a missing key. Drop after the SPA migration ships.
        doc["runtime"]       = currentRuntime;
        doc["total_runtime"] = totalRuntime;
        String out;
        serializeJson(doc, out);
        request->send(200, "application/json", out);
    });

    // Compile-time feature flags (formerly emitted inline as <script>const F={...}>).
    server.on("/api/features", HTTP_GET, [](AsyncWebServerRequest *request) {
        DynamicJsonDocument doc(256);
        doc["dmx"] = 1;
#ifdef RAVLIGHT_MODULE_DMX_PHYSICAL
        doc["dmxPhysical"] = 1;
#endif
#ifdef RAVLIGHT_MODULE_RECORDER
        doc["recorder"] = 1;
#endif
#ifdef RAVLIGHT_MODULE_TEMP
        doc["temp"] = 1;
#endif
#ifdef RAVLIGHT_MODULE_ETHERNET
        doc["ethernet"] = 1;
#endif
#ifdef RAVLIGHT_MODULE_DISCOVERY
        doc["discovery"] = 1;
#endif
#ifdef RAVLIGHT_MODULE_I2S_LED
        doc["i2s"] = 1;
#endif
#ifdef RAVLIGHT_MODULE_EFFECTS
        doc["effects"] = 1;
#endif
        doc["fixture"]    = PROJECT_NAME;
        doc["hw_outputs"] = HW_LED_OUTPUT_COUNT;
        JsonArray pins = doc.createNestedArray("hw_pins");
        for (int i = 0; i < HW_LED_OUTPUT_COUNT; i++) pins.add(HW_LED_OUTPUT_PINS[i]);
        String out;
        serializeJson(doc, out);
        request->send(200, "application/json", out);
    });

    // ── Proprietary OTA (ravlight.com feed) ──────────────────────────────────
    // GET  /api/ota        → current state (version, available, progress, notes)
    // POST /api/ota/check  → trigger a manifest re-check (non-blocking)
    // POST /api/ota/update → begin download+flash of the available image
    server.on("/api/ota", HTTP_GET, [](AsyncWebServerRequest *request) {
        const OtaState& s = otaGetState();
        DynamicJsonDocument doc(384);
        doc["current"]   = s.current;
        doc["latest"]    = s.latest;
        doc["notes"]     = s.notes;
        doc["checked"]   = s.checked;
        doc["checking"]  = s.checking;
        doc["available"] = s.available;
        doc["progress"]  = s.progress;
        doc["error"]     = s.error;
        String out;
        serializeJson(doc, out);
        request->send(200, "application/json", out);
    });
    server.on("/api/ota/check", HTTP_POST, [](AsyncWebServerRequest *request) {
        otaCheck();
        request->send(200, "application/json", "{\"ok\":true}");
    });
    server.on("/api/ota/update", HTTP_POST, [](AsyncWebServerRequest *request) {
        otaStartUpdate();
        request->send(200, "application/json", "{\"ok\":true}");
    });

    // POST /api/ota/upload — manual firmware/filesystem upload (our own OTA,
    // replaces ElegantOTA). The browser streams a .bin; we flash it onto the
    // inactive slot via the Arduino Update library. The uploaded filename
    // decides the target: names containing "littlefs"/"spiffs"/"_fs" go to the
    // filesystem partition, everything else is a firmware image. On success
    // the completion handler replies then schedules a reboot; the client shows
    // the same verification overlay used by the pull update.
    server.on("/api/ota/upload", HTTP_POST,
        [](AsyncWebServerRequest *request) {
            // Completion: the upload finished (final chunk seen) → reply + reboot.
            // If we never reached final (aborted / connection reset), Update is
            // still running — abort it so the dangling session doesn't hold flash
            // and degrade serving until the next reboot.
            bool ok = Update.isFinished() && !Update.hasError();
            if (!ok && Update.isRunning()) Update.abort();
            AsyncWebServerResponse *r = request->beginResponse(
                ok ? 200 : 500, "application/json",
                ok ? "{\"ok\":true}" : "{\"ok\":false}");
            r->addHeader("Connection", "close");
            request->send(r);
            if (ok) scheduleRestart();
        },
        [](AsyncWebServerRequest *request, const String& filename, size_t index,
           uint8_t *data, size_t len, bool final) {
            if (index == 0) {
                // A previous upload may have aborted mid-stream (reset) leaving
                // Update running — clear it before starting a fresh session so
                // retries are clean.
                if (Update.isRunning()) Update.abort();
                stopDMX();
                bool fs = filename.indexOf("littlefs") >= 0 ||
                          filename.indexOf("spiffs")   >= 0 ||
                          filename.indexOf("_fs")      >= 0;
                int cmd = fs ? U_SPIFFS : U_FLASH;
                ESP_LOGW("OTA", "manual upload start: %s (%s)",
                         filename.c_str(), fs ? "filesystem" : "firmware");
                if (!Update.begin(UPDATE_SIZE_UNKNOWN, cmd))
                    Update.printError(Serial);
            }
            if (!Update.hasError() && Update.write(data, len) != len)
                Update.printError(Serial);
            if (final) {
                if (Update.end(true))
                    ESP_LOGW("OTA", "manual upload done: %u bytes", index + len);
                else
                    Update.printError(Serial);
            }
        });

    // GET /update — minimal failsafe recovery page. Tiny, self-contained (no
    // external CSS/JS/images, no SPA, no fixture.js), so it still serves in one
    // small response when the device is memory-starved and the full UI won't
    // load — the way ElegantOTA's /update always worked. Uploads to
    // /api/ota/upload (our own Update.h handler). PROGMEM → no heap for content.
    server.on("/update", HTTP_GET, [](AsyncWebServerRequest *request) {
        static const char RECOVERY_HTML[] PROGMEM = R"HTML(<!doctype html><html><head>
<meta name="viewport" content="width=device-width,initial-scale=1"><title>RavLight recovery</title>
<style>body{background:#0a0a0a;color:#e2e2e2;font-family:sans-serif;max-width:420px;margin:36px auto;padding:0 16px;line-height:1.5}
h1{color:#e9ff00;font-size:18px}b{color:#fff}.btn{background:#e9ff00;color:#000;border:0;border-radius:8px;padding:12px 22px;font-weight:700;cursor:pointer;font-size:14px}
input[type=file]{width:100%;margin:14px 0;color:#888}#bar{height:8px;background:#333;border-radius:4px;overflow:hidden;margin:14px 0;display:none}#f{height:100%;width:0;background:#e9ff00;transition:width .2s}#s{color:#8a8a8a;font-size:13px}</style></head><body>
<h1>RavLight &mdash; firmware recovery</h1>
<p>Failsafe update. Choose an app-only <b>_fw_ .bin</b> and flash it &mdash; the device reboots when done. For a full USB reflash use the merged <b>_v_ .bin</b> instead.</p>
<input type="file" id="file" accept=".bin">
<button class="btn" onclick="up()">Flash firmware</button>
<div id="bar"><div id="f"></div></div><p id="s"></p>
<script>function up(){var fi=document.getElementById('file');if(!fi.files[0]){return;}
var fd=new FormData();fd.append('file',fi.files[0]);var x=new XMLHttpRequest();x.open('POST','/api/ota/upload');
document.getElementById('bar').style.display='block';
x.upload.onprogress=function(e){if(e.lengthComputable){var p=Math.round(e.loaded*100/e.total);document.getElementById('f').style.width=p+'%';document.getElementById('s').textContent='Uploading & writing '+p+'%';}};
x.onload=function(){document.getElementById('s').textContent=(x.status==200)?'Done — rebooting…':'Failed (HTTP '+x.status+')';};
x.onerror=function(){document.getElementById('s').textContent='Connection lost — device may be rebooting. Reload in ~15s.';};
x.send(fd);}</script></body></html>)HTML";
        request->send(200, "text/html", RECOVERY_HTML);
    });

    // GET /stats — runtime perf counters (render fps, mutex wait, heap, ArtNet pps).
    // POST /stats/reset — zero all accumulators for clean before/after measurement.
    server.on("/stats", HTTP_GET, [](AsyncWebServerRequest *request) {
        request->send(200, "application/json", stats_to_json());
    });
    server.on("/stats/reset", HTTP_POST, [](AsyncWebServerRequest *request) {
        stats_reset();
        request->send(200, "application/json", "{\"ok\":true}");
    });

    // POST /api/config — apply a JSON config blob and persist to NVS. Validates
    // before commit; returns {ok, restart_needed} so the client can decide whether
    // to POST /restart afterwards. Existing form-based /save endpoint remains for
    // backward compatibility while the SPA is rolled in.
    // The default DYNAMIC_JSON_DOCUMENT_SIZE (1024) isn't enough for the full
    // config blob — fixture sections (Elyon/Orion with N LED outputs) can push
    // raw JSON past 1 KB, and ArduinoJson needs 2-3× that for node storage.
    AsyncCallbackJsonWebHandler* postConfig = new AsyncCallbackJsonWebHandler(
        "/api/config",
        [](AsyncWebServerRequest *request, JsonVariant &body) {
            if (!body.is<JsonObject>()) {
                request->send(400, "application/json",
                              "{\"ok\":false,\"error\":\"invalid json\"}");
                return;
            }
            JsonObject doc = body.as<JsonObject>();
            bool restartNeeded = false;
            String restartReason;

            // ── Network section ────────────────────────────────────────────
            if (doc.containsKey("network")) {
                JsonObject net = doc["network"].as<JsonObject>();
                String newSsid    = net["ssid"]     | netConfig.wifiSSID;
                String newPwd     = net["password"] | netConfig.wifiPassword;
                bool   newDhcp    = net["dhcp"]     | netConfig.dhcp;
                String newIp      = net["ip"]       | netConfig.ip;
                String newSubnet  = net["subnet"]   | netConfig.subnet;
                String newGateway = net["gateway"]  | netConfig.gateway;
                if (newSsid != netConfig.wifiSSID ||
                    newPwd  != netConfig.wifiPassword ||
                    newDhcp != netConfig.dhcp ||
                    newIp   != netConfig.ip ||
                    newSubnet  != netConfig.subnet ||
                    newGateway != netConfig.gateway) {
                    netConfig.wifiSSID     = newSsid;
                    netConfig.wifiPassword = newPwd;
                    netConfig.dhcp         = newDhcp;
                    netConfig.ip           = newIp;
                    netConfig.subnet       = newSubnet;
                    netConfig.gateway      = newGateway;
                    restartNeeded = true;
                    if (restartReason.length() == 0) restartReason = "network";
                }
                // ESP-NOW opt-in: toggling it changes whether WiFi comes up at
                // boot, so it needs a restart to take effect.
                if (net.containsKey("espnow")) {
                    bool newEspnow = net["espnow"] | false;
                    if (newEspnow != netConfig.espnowEnabled) {
                        netConfig.espnowEnabled = newEspnow;
                        restartNeeded = true;
                        if (restartReason.length() == 0) restartReason = "espnow";
                    }
                }
            }

            // ── ID_fixture (mDNS hostname / AP SSID) ───────────────────────
            if (doc.containsKey("ID_fixture")) {
                String newId = doc["ID_fixture"] | setConfig.ID_fixture;
                if (newId != setConfig.ID_fixture && newId.length() > 0) {
                    setConfig.ID_fixture = newId;
                    restartNeeded = true;
                    if (restartReason.length() == 0) restartReason = "ID_fixture";
                }
            }

            // ── DMX section ────────────────────────────────────────────────
            if (doc.containsKey("dmx")) {
                JsonObject dmx = doc["dmx"].as<JsonObject>();
                uint8_t  newInput = dmx["input"]    | (uint8_t)dmxConfig.dmxInput;
                uint16_t newUniv  = dmx["universe"] | dmxConfig.startUniverse;
                bool     dmxInChanged = (newInput != dmxConfig.dmxInput) ||
                                        (newUniv  != dmxConfig.startUniverse);
                if (dmxInChanged) {
                    dmxConfig.dmxInput      = newInput;
                    dmxConfig.startUniverse = newUniv;
                    // Live switch: reinitDMXInput() tears down the old
                    // socket/driver and brings the new one up without
                    // touching the rest of the boot path. Tested on
                    // every transition between ArtNet / sACN / DMX
                    // wired / AutoScene / Effects.
                    registerDmxUniverse(dmxConfig.startUniverse);
                    reinitDMXInput();
                }
#ifdef RAVLIGHT_MODULE_DMX_PHYSICAL
                bool newOut = dmx["output"] | dmxConfig.dmxOutputEnabled;
                if (newOut != dmxConfig.dmxOutputEnabled) {
                    dmxConfig.dmxOutputEnabled = newOut;
                    restartNeeded = true;
                    if (restartReason.length() == 0) restartReason = "dmx_output";
                }
                // Live offset — the wire-send path re-reads dmxConfig.outOffset
                // on every frame, so no restart is needed to apply.
                uint16_t newOff = dmx["out_offset"] | dmxConfig.outOffset;
                if (newOff > 511) newOff = 511;
                dmxConfig.outOffset = newOff;
#endif
#ifdef RAVLIGHT_MODULE_RECORDER
                uint8_t newSlot = dmx["autoSceneSlot"] | dmxConfig.autoSceneSlot;
                if (newSlot != dmxConfig.autoSceneSlot) {
                    dmxConfig.autoSceneSlot = newSlot;
                }
#endif
#ifdef RAVLIGHT_MODULE_EFFECTS
                // Effects subobject — applied live (no restart needed). The
                // engine re-reads effectsConfig at the next tickEffects().
                if (dmx.containsKey("effects")) {
                    JsonObject fx = dmx["effects"].as<JsonObject>();
                    effectsConfig.effect      = fx["effect"]       | effectsConfig.effect;
                    effectsConfig.speed       = fx["speed"]        | effectsConfig.speed;
                    effectsConfig.r           = fx["r"]            | effectsConfig.r;
                    effectsConfig.g           = fx["g"]            | effectsConfig.g;
                    effectsConfig.b           = fx["b"]            | effectsConfig.b;
                    effectsConfig.intensity   = fx["intensity"]    | effectsConfig.intensity;
                    effectsConfig.rgbw_mode   = fx["rgbw"]         | effectsConfig.rgbw_mode;
                    effectsConfig.white       = fx["white"]        | effectsConfig.white;
                    effectsConfig.strobeRgb   = fx["strobe_rgb"]   | effectsConfig.strobeRgb;
                    effectsConfig.strobeWhite = fx["strobe_white"] | effectsConfig.strobeWhite;
                }
#endif
            }

            // ── Fixture section ────────────────────────────────────────────
            // Delegated to fixtureConfigDeserialize() which already understands
            // the on-disk JSON shape (outputs[]). Validation responsibility
            // currently sits in handleFixtureSaveParams's form path — for the SPA
            // path we trust the client and rely on saveConfig() not crashing on
            // bad values. A dedicated fixtureValidateJson() is a TODO.
            if (doc.containsKey("fixture")) {
                JsonObject fix = doc["fixture"].as<JsonObject>();
                fixtureConfigDeserialize(fix);
                // Let the fixture push live updates to its runtime; the return
                // value says whether changes still need a restart (e.g. LED
                // count/protocol changes that require RMT re-init).
                if (fixtureApplyLive()) {
                    restartNeeded = true;
                    if (restartReason.length() == 0) restartReason = "fixture";
                }
            }

            saveConfig();

            DynamicJsonDocument resp(192);
            resp["ok"]             = true;
            resp["restart_needed"] = restartNeeded;
            if (restartReason.length() > 0) resp["restart_reason"] = restartReason;
            String out;
            serializeJson(resp, out);
            request->send(200, "application/json", out);
        },
        4096);  // maxJsonBufferSize — full config blob can exceed 1 KB
    server.addHandler(postConfig);

    registerFixtureRoutes(server);

#ifdef RAVLIGHT_MODULE_DISCOVERY
    // Trigger a new UDP discovery scan (fire-and-forget — client polls /devices after delay)
    server.on("/discover", HTTP_GET, [](AsyncWebServerRequest *request) {
        bool withESPNow    = request->hasParam("espnow") &&
                             request->getParam("espnow")->value() == "1";
        bool wifiDisrupted = withESPNow && strcmp(getConnectionMode(), "WiFi") == 0;

        startCombinedDiscovery(withESPNow);

        char resp[80];
        snprintf(resp, sizeof(resp),
                 "{\"scanning\":true,\"duration\":%d,\"wifiDisrupted\":%s}",
                 DISC_SCAN_TOTAL_MS, wifiDisrupted ? "true" : "false");
        request->send(200, "application/json", resp);

        if (wifiDisrupted) {
            // Defer WiFi disconnect + ESP-NOW broadcast by 200 ms so the HTTP
            // response above has time to be delivered before WiFi drops.
            espnowScanTicker.once_ms(200, []() {
                suspendWiFiSTA();
                startESPNowDiscovery();
                triggerESPNowScanStart();
            });
        }
    });

    // Return current ScannedDevices as JSON array
    server.on("/devices", HTTP_GET, [](AsyncWebServerRequest *request) {
        const auto& devices = getDiscoveredUDPDevices();
        DynamicJsonDocument doc(2048);
        JsonArray arr = doc.to<JsonArray>();
        for (const auto& d : devices) {
            JsonObject obj = arr.createNestedObject();
            obj["fixture"] = d.fixture;
            obj["id"]      = d.id;
            obj["mode"]    = d.mode;
            obj["ip"]      = d.ip;
            obj["mac"]     = d.mac;
            obj["hwMac"]   = d.hwMac;   // non-empty → device was found via ESP-NOW
            obj["fw"]      = d.fw;
            obj["temp"]    = d.temp;
            obj["uptime"]  = d.uptime;
        }
        String resp;
        serializeJson(doc, resp);
        request->send(200, "application/json", resp);
    });

    // Send a command to a device: routes via ESP-NOW if hwmac is present, UDP otherwise
    server.on("/device-cmd", HTTP_POST, [](AsyncWebServerRequest *request) {
        if (!request->hasParam("ip", true) || !request->hasParam("command", true)) {
            request->send(400, "text/plain", "Missing ip or command");
            return;
        }
        String ip      = request->getParam("ip",      true)->value();
        String command = request->getParam("command", true)->value();
        String ssid, password;
        if (request->hasParam("ssid",     true)) ssid     = request->getParam("ssid",     true)->value();
        if (request->hasParam("password", true)) password = request->getParam("password", true)->value();
        // Autofill from this device's own WiFi credentials when the client
        // doesn't pass any — that's the "Send my WiFi" UX: the browser just
        // clicks a button, the password never travels back through the SPA.
        if (command == "CONNECT" && ssid.isEmpty()) {
            ssid     = netConfig.wifiSSID;
            password = netConfig.wifiPassword;
        }
        // Device discovered via ESP-NOW: route command back via ESP-NOW
        if (request->hasParam("hwmac", true) && !request->getParam("hwmac", true)->value().isEmpty()) {
            String hwMac = request->getParam("hwmac", true)->value();
            if (strcmp(getConnectionMode(), "WiFi") == 0) {
                // WiFi STA active — home channel = router channel, not AP_CHANNEL.
                // Defer: respond first, then suspend WiFi, send command, restore WiFi.
                strlcpy(s_pendingCmd.hwMac, hwMac.c_str(),    sizeof(s_pendingCmd.hwMac));
                strlcpy(s_pendingCmd.cmd,   command.c_str(),  sizeof(s_pendingCmd.cmd));
                strlcpy(s_pendingCmd.ssid,  ssid.c_str(),     sizeof(s_pendingCmd.ssid));
                strlcpy(s_pendingCmd.pwd,   password.c_str(), sizeof(s_pendingCmd.pwd));
                request->send(200, "text/plain", "queued");
                espnowCmdTicker.once_ms(200, []() {
                    suspendWiFiSTA();
                    sendESPNowCommand(s_pendingCmd.hwMac, s_pendingCmd.cmd,
                                      s_pendingCmd.ssid,  s_pendingCmd.pwd);
                    espnowCmdRestoreTicker.once_ms(500, resumeWiFiSTA);
                });
            } else {
                bool ok = sendESPNowCommand(hwMac, command, ssid, password);
                request->send(200, "text/plain", ok ? "sent" : "failed");
            }
            return;
        }
        // Device discovered via UDP: route command via UDP
        IPAddress target;
        if (!target.fromString(ip)) {
            request->send(400, "text/plain", "Invalid IP");
            return;
        }
        bool ok = sendUDPCommand(target, command, ssid, password);
        request->send(200, "text/plain", ok ? "sent" : "failed");
    });
#endif

    // --- DMX Monitor data endpoints ---
    server.on("/dmxdata", HTTP_GET, [](AsyncWebServerRequest *req) {
        uint16_t universe = 0;
        if (req->hasParam("universe")) universe = (uint16_t)req->getParam("universe")->value().toInt();

        uint8_t local[513] = {0};
        xSemaphoreTake(dmxBufferMutex, portMAX_DELAY);
        const uint8_t* buf = getUniverseData(universe);
        if (buf) memcpy(local + 1, buf + 1, 512);
        xSemaphoreGive(dmxBufferMutex);

        String out;
        out.reserve(2560);
        out += '[';
        for (int i = 1; i <= 512; i++) {
            out += local[i];
            if (i < 512) out += ',';
        }
        out += ']';
        req->send(200, "application/json", out);
    });

    server.on("/dmxmap", HTTP_GET, [](AsyncWebServerRequest *req) {
        DynamicJsonDocument doc(2048);
        JsonObject map = doc.createNestedObject("map");
        fixtureGetDmxMap(map);
        String respStr;
        serializeJson(doc, respStr);
        req->send(200, "application/json", respStr);
    });

    server.begin();
}

String readFile(fs::FS &fs, const char *path) {
    Serial.printf("[WS] Reading file: %s\n", path);
    File file = fs.open(path, "r");
    if (!file || file.isDirectory()) {
        Serial.println("[WS] Failed to open file");
        return String();
    }
    String content;
    content.reserve(file.size());   // single allocation — avoids repeated realloc+copy
    while (file.available()) content += (char)file.read();
    file.close();
    return content;
}

String requestWiFiNetworks() {
    return ScannedSSID;
}

void startWebServer() {
    server.begin();
}

void stopWebServer() {
    server.end();
}

void scheduleRestart() {
    restartTimer.once(2, []() {
        ESP.restart();
    });
}



