#ifdef RAVLIGHT_HAS_MOTOR
#include "core/motor/backends/Tmc2209LocalDriver.h"
#include <Arduino.h>
#include <string.h>
#include <esp_log.h>

static const char* TAG = "TMC2209Local";

// Periodic register read interval (ms)
static constexpr uint32_t REG_READ_INTERVAL_MS = 100;

// Ignore StallGuard for this long after a homing move starts — StallGuard
// readings are invalid during the initial acceleration ramp.
static constexpr uint32_t HOMING_STALL_BLANK_MS = 500;

// EN pin polarity: TMC2209 EN is active LOW
static constexpr uint8_t EN_ENABLE  = LOW;
static constexpr uint8_t EN_DISABLE = HIGH;

// ─── Constructor / Destructor ────────────────────────────────────────────────

Tmc2209LocalDriver::Tmc2209LocalDriver(HardwareSerial& serial,
                                       uint8_t  tmc_address,
                                       uint8_t  step_pin,
                                       uint8_t  dir_pin,
                                       uint8_t  en_pin,
                                       uint8_t  rx_pin,
                                       uint8_t  tx_pin,
                                       uint8_t  diag_pin,
                                       float    r_sense,
                                       uint32_t uart_baud)
    : _serial(serial),
      _tmc_addr(tmc_address),
      _step_pin(step_pin), _dir_pin(dir_pin), _en_pin(en_pin),
      _rx_pin(rx_pin), _tx_pin(tx_pin), _diag_pin(diag_pin),
      _r_sense(r_sense), _uart_baud(uart_baud)
{}

Tmc2209LocalDriver::~Tmc2209LocalDriver() {
    end();
}

// ─── Lifecycle ───────────────────────────────────────────────────────────────

bool Tmc2209LocalDriver::begin() {
    // Configure output pins — keep driver disabled until fully initialised
    pinMode(_en_pin,   OUTPUT); digitalWrite(_en_pin,   EN_DISABLE);
    pinMode(_step_pin, OUTPUT); digitalWrite(_step_pin, LOW);
    pinMode(_dir_pin,  OUTPUT); digitalWrite(_dir_pin,  LOW);
    pinMode(_diag_pin, INPUT);

    // UART for TMCStepper — half-duplex PDN_UART
    _serial.begin(_uart_baud, SERIAL_8N1, _rx_pin, _tx_pin);
    delay(50);

    // TMC2209 via TMCStepper
    _tmc = new TMC2209Stepper(&_serial, _r_sense, _tmc_addr);
    _tmc->begin();
    _tmc->toff(4);                      // chopper off-time: enables driver output stage
    _tmc->blank_time(24);               // recommended for most motors
    _tmc->rms_current(_run_ma);         // initial run current
    _tmc->microsteps(16);               // 1/16 microstepping
    _tmc->en_spreadCycle(false);        // StealthChop (quieter at low speed)
    _tmc->pwm_autoscale(true);          // automatic current scaling
    _tmc->TCOOLTHRS(0xFFFFF);           // enable CoolStep / StallGuard at all speeds

    // Verify UART communication
    if (_tmc->test_connection() != 0) {
        ESP_LOGE(TAG, "TMC2209 UART not responding (addr=%d)", _tmc_addr);
        return false;
    }
    ESP_LOGI(TAG, "TMC2209 addr=%d ok, version=0x%02X", _tmc_addr, _tmc->version());

    // FastAccelStepper — step pulses generated by ESP32 hardware (MCPWM/RMT).
    _engine.init();
    _stepper = _engine.stepperConnectToPin(_step_pin);
    if (!_stepper) {
        ESP_LOGE(TAG, "FastAccelStepper: no step-gen hardware free for GPIO%d", _step_pin);
        return false;
    }
    _stepper->setDirectionPin(_dir_pin);
    _stepper->setSpeedInHz(2000);     // overridden by setSpeed()
    _stepper->setAcceleration(1000);  // overridden by setAccel()

    // DIAG interrupt — RISING edge when TMC2209 detects stall
    attachInterruptArg(digitalPinToInterrupt(_diag_pin), _diagIsrCb, this, RISING);

    // Enable driver
    digitalWrite(_en_pin, EN_ENABLE);
    _state       = MotorState::IDLE;
    _fault_flags = 0;
    _homed       = false;
    return true;
}

void Tmc2209LocalDriver::end() {
    if (_diag_pin < 255)
        detachInterrupt(digitalPinToInterrupt(_diag_pin));

    if (_stepper) _stepper->forceStop();
    digitalWrite(_en_pin, EN_DISABLE);
    _state = MotorState::DRIVER_OFF;

    // FastAccelStepper instances are owned by the engine — not deleted here.
    _stepper = nullptr;
    delete _tmc; _tmc = nullptr;
}

// ─── Motion ──────────────────────────────────────────────────────────────────

void Tmc2209LocalDriver::moveTo(int32_t position) {
    if (_state == MotorState::FAULT || _state == MotorState::DRIVER_OFF) return;

    // Apply soft limits — clamp target into [min, max]
    if (_soft_limits_enabled) {
        if (position < _soft_min) {
            ESP_LOGW(TAG, "moveTo %d clamped to soft_min %d", position, _soft_min);
            position = _soft_min;
        } else if (position > _soft_max) {
            ESP_LOGW(TAG, "moveTo %d clamped to soft_max %d", position, _soft_max);
            position = _soft_max;
        }
    }

    _stepper->moveTo(position);
    if (position != _stepper->getCurrentPosition())
        _state = MotorState::MOVING;
}

void Tmc2209LocalDriver::moveBy(int32_t delta) {
    moveTo(_stepper->getCurrentPosition() + delta);
}

void Tmc2209LocalDriver::setSpeed(float steps_per_sec) {
    uint32_t hz = (steps_per_sec > 1.0f) ? (uint32_t)steps_per_sec : 1;
    _stepper->setSpeedInHz(hz);
}

void Tmc2209LocalDriver::setAccel(float steps_per_sec2) {
    uint32_t a = (steps_per_sec2 > 1.0f) ? (uint32_t)steps_per_sec2 : 1;
    _stepper->setAcceleration(a);
}

void Tmc2209LocalDriver::stop() {
    // Decelerated stop — applies to both ramped moves and constant-velocity jog.
    _stepper->stopMove();
    if (_state == MotorState::JOGGING)
        _state = MotorState::IDLE;
}

void Tmc2209LocalDriver::jog(int8_t direction, float speed_sps) {
    if (_state == MotorState::FAULT || _state == MotorState::DRIVER_OFF) {
        ESP_LOGW(TAG, "jog rejected: driver not ready (state=%d)", (int)_state);
        return;
    }
    if (direction == 0 || speed_sps <= 0.0f) {
        stop();
        return;
    }
    uint32_t hz = (speed_sps > 1.0f) ? (uint32_t)speed_sps : 1;
    _stepper->setSpeedInHz(hz);
    if (direction > 0) _stepper->runForward();
    else               _stepper->runBackward();
    _state = MotorState::JOGGING;
}

void Tmc2209LocalDriver::estop() {
    // Immediate stop (no deceleration ramp) — then cut driver enable
    _stepper->forceStop();
    digitalWrite(_en_pin, EN_DISABLE);
    _state       = MotorState::FAULT;
    _fault_flags |= (uint8_t)MotorFault::DRIVER_ERROR;
    ESP_LOGW(TAG, "E-STOP triggered");
}

// ─── Soft limits + fault recovery ────────────────────────────────────────────

void Tmc2209LocalDriver::setSoftLimits(int32_t min_pos, int32_t max_pos) {
    if (min_pos >= max_pos) {
        ESP_LOGW(TAG, "setSoftLimits ignored: min (%d) >= max (%d)", min_pos, max_pos);
        return;
    }
    _soft_min            = min_pos;
    _soft_max            = max_pos;
    _soft_limits_enabled = true;
    ESP_LOGI(TAG, "soft limits enabled: [%d, %d]", _soft_min, _soft_max);
}

void Tmc2209LocalDriver::disableSoftLimits() {
    _soft_limits_enabled = false;
    ESP_LOGI(TAG, "soft limits disabled");
}

bool Tmc2209LocalDriver::clearFault() {
    if (_state != MotorState::FAULT && _state != MotorState::DRIVER_OFF) {
        // Nothing to clear — but still reset flags in case they accumulated
        _fault_flags = 0;
        return true;
    }
    if (!_tmc) {
        ESP_LOGE(TAG, "clearFault: driver not initialised");
        return false;
    }

    // Re-read driver registers to check whether sticky faults still active
    _readRegisters();

    // Sticky conditions: overtemperature must clear, driver must respond on UART
    if (_fault_flags & (uint8_t)MotorFault::OVERTEMP) {
        ESP_LOGW(TAG, "clearFault: overtemperature still active — refusing to clear");
        return false;
    }
    if (_tmc->test_connection() != 0) {
        ESP_LOGW(TAG, "clearFault: UART not responding — refusing to clear");
        _fault_flags |= (uint8_t)MotorFault::DRIVER_ERROR;
        return false;
    }

    // All sticky conditions cleared — reset flags, re-enable, return to IDLE
    _fault_flags = 0;
    _stall_isr_flag = false;
    digitalWrite(_en_pin, EN_ENABLE);
    _state = MotorState::IDLE;
    ESP_LOGI(TAG, "fault cleared, driver re-enabled");
    return true;
}

// ─── Homing ──────────────────────────────────────────────────────────────────

void Tmc2209LocalDriver::startHoming() {
    if (_state == MotorState::FAULT || _state == MotorState::DRIVER_OFF) {
        ESP_LOGW(TAG, "startHoming: driver not ready (state=%d)", (int)_state);
        return;
    }
    if (!_tmc || !_stepper) return;

    // Apply reduced current directly — do NOT update _run_ma so restore in _updateHoming works
    float hold_mult = (_hcfg.current_ma > 0)
                      ? (float)_hold_ma / _hcfg.current_ma : 0.0f;
    _tmc->rms_current(_hcfg.current_ma, hold_mult);
    _tmc->SGTHRS(_hcfg.sgthrs);

    // Clear any stale stall flag before we start moving
    _stall_isr_flag = false;

    // Constant-speed travel toward the end stop.
    _stepper->setSpeedInHz(_hcfg.speed > 1 ? _hcfg.speed : 1);
    if (_hcfg.direction > 0) _stepper->runForward();
    else                     _stepper->runBackward();

    _homing_start_ms = millis();
    _homing_phase    = HomingPhase::MOVING;
    _state           = MotorState::HOMING;
    ESP_LOGI(TAG, "homing started: dir=%d speed=%u sgthrs=%u current=%u mA",
             _hcfg.direction, _hcfg.speed, _hcfg.sgthrs, _hcfg.current_ma);
}

void Tmc2209LocalDriver::setHomePosition() {
    _stepper->forceStopAndNewPosition(0);
    _homed = true;
    ESP_LOGI(TAG, "home position set (step counter reset to 0)");
}

void Tmc2209LocalDriver::setHomingConfig(const HomingConfig& cfg) {
    _hcfg = cfg;
    ESP_LOGI(TAG, "homing config: dir=%d speed=%u sgthrs=%u current=%u backoff=%u",
             cfg.direction, cfg.speed, cfg.sgthrs, cfg.current_ma, cfg.backoff_steps);
}

// ─── Current control ─────────────────────────────────────────────────────────

void Tmc2209LocalDriver::setRunCurrent(uint16_t ma) {
    _run_ma = ma;
    if (_tmc) {
        float hold_mult = (_run_ma > 0) ? (float)_hold_ma / _run_ma : 0.0f;
        _tmc->rms_current(_run_ma, hold_mult);
    }
}

void Tmc2209LocalDriver::setHoldCurrent(uint16_t ma) {
    _hold_ma = ma;
    setRunCurrent(_run_ma);  // re-applies hold multiplier
}

// ─── StallGuard — Fase 4 stubs ───────────────────────────────────────────────

void Tmc2209LocalDriver::setStallGuardThreshold(uint8_t threshold) {
    if (_tmc) _tmc->SGTHRS(threshold);
}

uint16_t Tmc2209LocalDriver::getStallGuardResult() {
    return _sg_result;
}

// Run the motor at homing speed with the stall fault suppressed, so the operator
// can load the shaft and watch SG_RESULT (SGCAL log) without tripping a FAULT.
void Tmc2209LocalDriver::startStallGuardCal(int8_t direction) {
    if (_state == MotorState::FAULT || _state == MotorState::DRIVER_OFF) {
        ESP_LOGW(TAG, "startStallGuardCal: driver not ready (state=%d)", (int)_state);
        return;
    }
    if (!_stepper) return;
    _sg_cal         = true;
    _stall_isr_flag = false;
    _stepper->setSpeedInHz(_hcfg.speed > 1 ? _hcfg.speed : 1);
    if (direction >= 0) _stepper->runForward();
    else                _stepper->runBackward();
    _state = MotorState::JOGGING;
    ESP_LOGI(TAG, "StallGuard calibration started (speed=%u dir=%d)", _hcfg.speed, (int)direction);
}

void Tmc2209LocalDriver::stopStallGuardCal() {
    _sg_cal = false;
    if (_stepper) _stepper->stopMove();
    if (_state == MotorState::JOGGING) _state = MotorState::IDLE;
    ESP_LOGI(TAG, "StallGuard calibration stopped");
}

// ─── Status ──────────────────────────────────────────────────────────────────

MotorStatus Tmc2209LocalDriver::getStatus() {
    MotorStatus s;
    s.state       = _state;
    s.position    = _stepper ? _stepper->getCurrentPosition() : 0;
    s.speed       = _stepper ? (_stepper->getCurrentSpeedInMilliHz() / 1000.0f) : 0.0f;
    s.fault_flags = _fault_flags;
    s.sg_result   = _sg_result;
    s.driver_temp = _driver_temp;
    s.homed       = _homed;
    return s;
}

bool Tmc2209LocalDriver::isBusy() {
    return _stepper && _stepper->isRunning();
}

bool Tmc2209LocalDriver::hasFeature(const char* feature) {
    if (strcmp(feature, "stallguard")  == 0) return true;
    if (strcmp(feature, "coolstep")    == 0) return true;
    if (strcmp(feature, "uart_config") == 0) return true;
    return false;
}

// ─── Update loop ─────────────────────────────────────────────────────────────

void Tmc2209LocalDriver::update() {
    if (!_stepper || !_tmc) return;

    // Step pulses are generated by FastAccelStepper in hardware — update() only
    // advances the homing state machine, detects stalls and polls TMC registers.
    if (_state == MotorState::HOMING) {
        _updateHoming();
    } else if (_state == MotorState::JOGGING) {
        // Stall during jog → e-stop. During a StallGuard calibration run the stall
        // is expected (operator loads the shaft) — suppress the fault.
        if (_stall_isr_flag) {
            _stall_isr_flag = false;
            if (!_sg_cal) {
                _stepper->forceStop();
                _fault_flags |= (uint8_t)MotorFault::STALL;
                _state = MotorState::FAULT;
                ESP_LOGW(TAG, "stall during jog — entering FAULT");
            }
        }
    } else {
        // Transition to IDLE when a ramped move reaches its target
        if (_state == MotorState::MOVING &&
            _stepper->getCurrentPosition() == _stepper->targetPos())
            _state = MotorState::IDLE;

        // Stall outside homing is a fault
        if (_stall_isr_flag) {
            _stall_isr_flag = false;
            _stepper->forceStop();
            _fault_flags |= (uint8_t)MotorFault::STALL;
            _state = MotorState::FAULT;
            ESP_LOGW(TAG, "stall detected via DIAG pin");
        }
    }

    // Periodic TMC register read (driver status + StallGuard result)
    uint32_t now = millis();
    if (now - _last_reg_ms >= REG_READ_INTERVAL_MS) {
        _last_reg_ms = now;
        _readRegisters();
        // StallGuard calibration aid — while the motor moves, stream SG_RESULT at
        // 10 Hz so the operator can read the free-running vs loaded band and pick a
        // homing SGTHRS. Jog free, then hold the shaft and watch SG drop toward 0.
        if (_state == MotorState::JOGGING || _state == MotorState::HOMING ||
            _state == MotorState::MOVING) {
            ESP_LOGI(TAG, "SGCAL sg=%u state=%d", (unsigned)_sg_result, (int)_state);
        }
    }
}

// ─── Homing state machine ────────────────────────────────────────────────────

void Tmc2209LocalDriver::_updateHoming() {
    switch (_homing_phase) {

    case HomingPhase::MOVING:
        // StallGuard is invalid during the initial acceleration ramp — ignore
        // any stall for a blanking window after the homing move starts.
        if (millis() - _homing_start_ms < HOMING_STALL_BLANK_MS) {
            _stall_isr_flag = false;
            break;
        }
        // Constant-velocity travel runs in hardware; just watch for the stall.
        if (_stall_isr_flag) {
            _stall_isr_flag = false;

            // End stop reached — stop and zero the position counter
            _stepper->forceStopAndNewPosition(0);

            // Restore operational current and SGTHRS
            setRunCurrent(_run_ma);
            _tmc->SGTHRS(_hcfg.op_sgthrs);

            // Retreat from the end stop (ramped move away from it)
            _stepper->setSpeedInHz(_hcfg.speed > 1 ? _hcfg.speed : 1);
            _stepper->moveTo((int32_t)_hcfg.backoff_steps * -_hcfg.direction);
            _homing_phase = HomingPhase::BACKOFF;
            ESP_LOGI(TAG, "stall at end stop — backing off %u steps", _hcfg.backoff_steps);
        }
        break;

    case HomingPhase::BACKOFF:
        if (_stepper->getCurrentPosition() == _stepper->targetPos()) {
            // Back-off complete — declare home at current position
            _stepper->setCurrentPosition(0);
            _homed        = true;
            _homing_phase = HomingPhase::IDLE;
            _state        = MotorState::IDLE;
            ESP_LOGI(TAG, "homing complete — home position set");
        }
        break;

    case HomingPhase::IDLE:
    default:
        break;
    }
}

// ─── Private helpers ─────────────────────────────────────────────────────────

void Tmc2209LocalDriver::_readRegisters() {
    _sg_result = _tmc->SG_RESULT();

    // DRV_STATUS contains overtemp, short-circuit flags and load estimate
    uint32_t drv_raw = _tmc->DRV_STATUS();
    bool ot   = (drv_raw >> 25) & 0x1;   // over-temperature shutdown
    bool otpw = (drv_raw >> 26) & 0x1;   // over-temperature warning
    bool s2ga = (drv_raw >> 27) & 0x1;   // short to GND phase A
    bool s2gb = (drv_raw >> 28) & 0x1;   // short to GND phase B

    if (ot || otpw) {
        _fault_flags |= (uint8_t)MotorFault::OVERTEMP;
        _driver_temp  = ot ? 150 : 120;   // rough estimate; TMC2209 has no ADC
        if (ot) ESP_LOGE(TAG, "TMC2209 overtemperature shutdown!");
    }
    if (s2ga || s2gb) {
        _fault_flags |= (uint8_t)MotorFault::OVERCURRENT;
        ESP_LOGE(TAG, "TMC2209 short to GND detected");
    }
}

void IRAM_ATTR Tmc2209LocalDriver::_diagIsrCb(void* arg) {
    Tmc2209LocalDriver* drv = static_cast<Tmc2209LocalDriver*>(arg);
    drv->_stall_isr_flag = true;
}

#endif // RAVLIGHT_HAS_MOTOR
